syntax = "proto3";
package MF26.v2;

import "MF26/v2/vehicle.proto";
import "MF26/v2/control.proto";
import "MF26/v2/logging.proto";
import "MF26/v2/daq.proto";
import "MF26/v2/timestamp.proto";


message Ack {
    bool   ok              = 1;
    string message         = 2;
}
message StreamRequest  { 
    string car_id          = 1; 
}
message SessionRequest {
    string session_id      = 1; 
}

message TimeSync {
  Timestamp current_time   = 1;
  string source            = 2;  // e.g. "gps", "ntp", "system"
}

service DataService {
    
  rpc StreamTimeSync(StreamRequest)   returns (stream TimeSync);

  rpc PushDAQData(DAQData)            returns (Ack);


  rpc StreamCarFrames(StreamRequest)  returns (stream CarFrame);

  rpc SendCommand(VCUCommand)         returns (Ack);

  rpc GetSession(SessionRequest)      returns (stream LoggedSession);
}